# Generated by Django 4.2.3 on 2024-01-02 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masterApi', '0002_alter_mstbloodgroup_createdby_and_more'),
        ('jdcApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedbackTitleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackTitles', to='masterApi.mstfeedbacktitle'),
        ),
        migrations.DeleteModel(
            name='MstFeedbackTitle',
        ),
    ]
