# Generated by Django 4.2.3 on 2024-01-02 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jdcApi', '0002_alter_feedback_feedbacktitleid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aarti',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_aarti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aarti',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_aarti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appconfigurations',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_app_configuration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appconfigurations',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_app_configuration', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='area',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='area',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_area', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='business',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_business', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='city',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_city', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthan',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dharam_sthan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthan',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_dharam_sthan', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthanhistory',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dharam_sthan_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthanhistory',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_dharam_sthan_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthanmember',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_dharam_sthan_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dharamsthanmember',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_dharam_sthan_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_emergency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_emergency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_feedback', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literature',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_literature', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literature',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_literature', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literaturedocument',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_literature_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='literaturedocument',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_literature_document', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_live_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='livelocation',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_live_location', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saint',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_saint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saint',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_saint', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_state', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='state',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_state', to=settings.AUTH_USER_MODEL),
        ),
    ]
