# Generated by Django 4.2.3 on 2023-10-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0005_sect_saint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sect',
            name='sectName',
            field=models.CharField(max_length=20),
        ),
    ]
