# Generated by Django 4.2.3 on 2023-10-30 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0007_delete_saint_delete_sect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sect',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sectName', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('fatherName', models.CharField(max_length=30)),
                ('motherName', models.CharField(max_length=30)),
                ('birthPlace', models.CharField(max_length=30)),
                ('dikshaPlace', models.CharField(max_length=30)),
                ('guruName', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('devlokDate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('selectSect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_sect', to='jdcApi.sect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
