# Generated by Django 4.2.3 on 2023-10-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0008_sect_saint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sect',
            name='sectName',
            field=models.CharField(choices=[('Digambar', 'Digambar'), ('Terapanthi', 'Terapanthi'), ('Svetambar', 'Svetambar'), ('Murtipujaka', 'Murtipujaka')], max_length=20),
        ),
    ]
