# Generated by Django 4.2.3 on 2023-10-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0011_saint'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='isVerified',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
