# Generated by Django 4.2.3 on 2023-10-31 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0012_saint_isverified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
