# Generated by Django 4.2.3 on 2023-11-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0013_alter_saint_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saint',
            name='devlokDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
