# Generated by Django 4.2.3 on 2023-11-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0017_mstbloodgroup_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbloodgroup',
            name='order',
            field=models.IntegerField(),
        ),
    ]
