# Generated by Django 4.2.3 on 2023-11-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0018_alter_mstbloodgroup_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MstDoctor',
        ),
        migrations.DeleteModel(
            name='MstRelation',
        ),
        migrations.RemoveField(
            model_name='mstmaritalstatus',
            name='maritalStatus',
        ),
        migrations.AddField(
            model_name='mstmaritalstatus',
            name='maritalStatusName',
            field=models.CharField(default=1, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='mstmaritalstatus',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
