# Generated by Django 4.2.3 on 2023-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0019_delete_mstdoctor_delete_mstrelation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstmaritalstatus',
            name='maritalStatusName',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='mstmaritalstatus',
            name='order',
            field=models.IntegerField(),
        ),
    ]
