# Generated by Django 4.2.3 on 2023-11-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0022_mstprofession'),
    ]

    operations = [
        migrations.AddField(
            model_name='sect',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sect',
            name='sectName',
            field=models.CharField(max_length=20),
        ),
    ]
