# Generated by Django 4.2.3 on 2023-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0023_sect_order_alter_sect_sectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sect',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sect',
            name='sectName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
