# Generated by Django 4.2.3 on 2023-11-17 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0024_alter_sect_order_alter_sect_sectname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sect',
            new_name='MstSect',
        ),
    ]
