# Generated by Django 4.2.3 on 2023-11-17 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0025_rename_sect_mstsect'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saint',
            old_name='selectSect',
            new_name='sectId',
        ),
    ]
