# Generated by Django 4.2.3 on 2023-11-24 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0026_rename_selectsect_saint_sectid'),
    ]

    operations = [
        migrations.AddField(
            model_name='saint',
            name='devlokTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saint',
            name='dobTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='areaContactNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='areaMC',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='landmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='business',
            name='businessPhoneNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='gstNumber',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='business',
            name='website',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='stateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='jdcApi.state'),
        ),
        migrations.AlterField(
            model_name='saint',
            name='devlokDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saint',
            name='dob',
            field=models.DateField(),
        ),
    ]
