# Generated by Django 4.2.3 on 2023-11-28 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0029_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='literature',
            old_name='literatureId',
            new_name='id',
        ),
        migrations.AddField(
            model_name='literature',
            name='sectId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jdcApi.mstsect'),
        ),
    ]
