# Generated by Django 4.2.3 on 2023-11-29 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0031_alter_literature_sectid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aarti',
            old_name='aartiId',
            new_name='id',
        ),
        migrations.AddField(
            model_name='aarti',
            name='sectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jdcApi.mstsect'),
        ),
    ]
