# Generated by Django 4.2.3 on 2023-11-29 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0032_rename_aartiid_aarti_id_aarti_sectid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aarti',
        ),
    ]
