# Generated by Django 4.2.3 on 2023-11-29 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0033_delete_aarti'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aarti',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aartiName', models.CharField(max_length=200)),
                ('aartiText', models.TextField()),
                ('isVerified', models.BooleanField(default=False)),
                ('sectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.mstsect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
