# Generated by Django 4.2.3 on 2023-11-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0034_aarti'),
    ]

    operations = [
        migrations.AddField(
            model_name='aarti',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
