# Generated by Django 4.2.3 on 2023-11-29 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0035_aarti_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aarti',
        ),
    ]
