# Generated by Django 4.2.3 on 2023-11-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0037_aarti'),
    ]

    operations = [
        migrations.CreateModel(
            name='DharamSthan',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('locationLink', models.TextField(blank=True, null=True)),
                ('postalCode', models.CharField(max_length=10)),
                ('foundationDate', models.DateField(blank=True, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('ifcsCode', models.CharField(blank=True, max_length=30, null=True)),
                ('upiId', models.CharField(blank=True, max_length=50, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('cityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.city')),
                ('sectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.mstsect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
