# Generated by Django 4.2.3 on 2023-11-30 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0038_dharamsthan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dharamsthan',
            old_name='ifcsCode',
            new_name='ifscCode',
        ),
    ]
