# Generated by Django 4.2.3 on 2023-12-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0039_rename_ifcscode_dharamsthan_ifsccode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DharamSthanMember',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=15)),
                ('isVerified', models.BooleanField(default=False)),
                ('dharamSthanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.dharamsthan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
