# Generated by Django 4.2.3 on 2023-12-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0040_dharamsthanmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='dharamsthanmember',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
