# Generated by Django 4.2.3 on 2023-12-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0042_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='areaContactNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
