# Generated by Django 4.2.3 on 2023-12-06 09:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0043_alter_area_areacontactnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='DharamSthanHistory',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('isVerified', models.BooleanField(default=False)),
                ('dharamSthanId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.dharamsthan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
