# Generated by Django 4.2.3 on 2023-12-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0044_dharamsthanhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dharamsthanhistory',
            name='isVerified',
        ),
    ]
