# Generated by Django 4.2.3 on 2023-12-07 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0045_remove_dharamsthanhistory_isverified'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=70)),
                ('person1Name', models.CharField(max_length=50)),
                ('phoneNumber1', models.CharField(max_length=15)),
                ('person2Name', models.CharField(blank=True, max_length=50, null=True)),
                ('phoneNumber2', models.CharField(blank=True, max_length=15, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('locationLink', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isVerified', models.BooleanField(default=False)),
                ('sectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jdcApi.mstsect')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
