# Generated by Django 4.2.3 on 2023-12-08 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0047_literaturedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturedocument',
            name='isVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='literaturedocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='literature_Documents', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='literaturedocument',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
