# Generated by Django 4.2.3 on 2023-12-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0048_literaturedocument_isverified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='literaturedocument',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
