# Generated by Django 4.2.3 on 2023-12-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0049_literaturedocument_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfigurations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('configurationKey', models.CharField(max_length=50)),
                ('configurationValue', models.BooleanField()),
                ('createdBy', models.IntegerField()),
                ('updatedBy', models.IntegerField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
