# Generated by Django 4.2.3 on 2023-12-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0054_rename_feedbacktitleid_feedback_feedbacktitleid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedbackTitle',
            new_name='MstFeedbackTitle',
        ),
    ]
