# Generated by Django 4.2.3 on 2023-12-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jdcApi', '0055_rename_feedbacktitle_mstfeedbacktitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='createdBy',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updatedBy',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
