# Generated by Django 4.2.3 on 2024-01-02 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbloodgroup',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_blood_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstbloodgroup',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_blood_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstfeedbacktitle',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_feedback_titles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstfeedbacktitle',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_feedback_titles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstmaritalstatus',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_marital_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstmaritalstatus',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_marital_status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstprofession',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_professions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstprofession',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_professions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstrelation',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstrelation',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_relations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstsect',
            name='createdBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_sects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mstsect',
            name='updatedBy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_sects', to=settings.AUTH_USER_MODEL),
        ),
    ]
