# Generated by Django 4.2.3 on 2024-01-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterApi', '0002_alter_mstbloodgroup_createdby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mstbloodgroup',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mstfeedbacktitle',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mstmaritalstatus',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mstprofession',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mstrelation',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mstsect',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
