# Generated by Django 4.2.3 on 2023-09-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('dob', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('areaId', models.CharField(default=1, max_length=10, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('cityId', models.CharField(default=1, max_length=10)),
                ('currentAddress', models.CharField(max_length=200, null=True)),
                ('emailId', models.CharField(blank=True, max_length=120, null=True)),
                ('fatherName', models.CharField(max_length=50)),
                ('fmcToken', models.TextField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('gotra', models.CharField(blank=True, max_length=30, null=True)),
                ('headId', models.IntegerField(default=None, null=True)),
                ('lookingForMatch', models.BooleanField(default=False)),
                ('maritalStatus', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('nativePlace', models.CharField(blank=True, max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('phoneNumberVisibility', models.BooleanField(default=True)),
                ('profession', models.CharField(max_length=20, null=True)),
                ('relationWithHead', models.CharField(max_length=50)),
                ('sect', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('status', models.CharField(default='active', max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
