# Generated by Django 4.2.3 on 2023-09-09 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('isActive', models.BooleanField(default=False)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('areaId', models.CharField(default=1, max_length=10, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('cityId', models.CharField(default=1, max_length=10)),
                ('currentAddress', models.CharField(max_length=200, null=True)),
                ('emailId', models.CharField(blank=True, max_length=120, null=True)),
                ('fatherName', models.CharField(max_length=50)),
                ('fmcToken', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('gotra', models.CharField(blank=True, max_length=30, null=True)),
                ('lookingForMatch', models.BooleanField(default=False)),
                ('maritalStatus', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50, null=True)),
                ('nativePlace', models.CharField(blank=True, max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=12, unique=True)),
                ('phoneNumberVisibility', models.BooleanField(default=True)),
                ('profession', models.CharField(max_length=20, null=True)),
                ('relationWithHead', models.CharField(max_length=50)),
                ('sect', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('headId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
