# Generated by Django 4.2.3 on 2024-01-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('phoneNumberVisibility', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=10)),
                ('gotra', models.CharField(blank=True, max_length=30, null=True)),
                ('nativePlace', models.CharField(blank=True, max_length=30, null=True)),
                ('currentAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('fatherName', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('lookingForMatch', models.BooleanField(default=False)),
                ('dob', models.DateField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=6)),
                ('status', models.CharField(default='active', max_length=10)),
                ('count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
