# Generated by Django 4.2.3 on 2024-01-01 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('masterApi', '0001_initial'),
        ('jdcApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areaId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jdcApi.area'),
        ),
        migrations.AddField(
            model_name='user',
            name='bloodGroupId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.mstbloodgroup'),
        ),
        migrations.AddField(
            model_name='user',
            name='cityId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jdcApi.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='headId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalStatusId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.mstmaritalstatus'),
        ),
        migrations.AddField(
            model_name='user',
            name='professionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.mstprofession'),
        ),
        migrations.AddField(
            model_name='user',
            name='relationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.mstrelation'),
        ),
        migrations.AddField(
            model_name='user',
            name='sectId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='masterApi.mstsect'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
