# Generated by Django 4.2.3 on 2023-09-22 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('isActive', models.BooleanField(default=True)),
                ('groupId', models.CharField(default=1, max_length=40)),
                ('createdBy', models.CharField(default=1, max_length=50)),
                ('updatedBy', models.CharField(default=1, max_length=50)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('areaId', models.CharField(default=1, max_length=10, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=5, null=True)),
                ('cityId', models.CharField(default=1, max_length=10)),
                ('currentAddress', models.CharField(blank=True, max_length=200, null=True)),
                ('emailId', models.CharField(blank=True, max_length=120, null=True)),
                ('fatherName', models.CharField(max_length=50)),
                ('fcmToken', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('gotra', models.CharField(blank=True, max_length=30, null=True)),
                ('headId', models.IntegerField(blank=True, default=None, null=True)),
                ('lookingForMatch', models.BooleanField(default=False)),
                ('maritalStatus', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=50)),
                ('nativePlace', models.CharField(blank=True, max_length=30, null=True)),
                ('phoneNumber', models.CharField(max_length=12)),
                ('phoneNumberVisibility', models.BooleanField(default=True)),
                ('profession', models.CharField(blank=True, max_length=20, null=True)),
                ('relationWithHead', models.CharField(blank=True, max_length=50)),
                ('sect', models.CharField(max_length=20)),
                ('isAdmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
