# Generated by Django 4.2.3 on 2023-09-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_notificationhistory_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='fcmToken',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
