# Generated by Django 4.2.3 on 2023-10-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_userid_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationWithHead',
            field=models.CharField(max_length=50),
        ),
    ]
