# Generated by Django 4.2.3 on 2023-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_relationwithhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sect',
        ),
        migrations.AddField(
            model_name='user',
            name='sectId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='areaId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='fatherName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='maritalStatus',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
