# Generated by Django 4.2.3 on 2023-11-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_user_sect_user_sectid_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areaId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityId',
            field=models.IntegerField(default=None),
        ),
    ]
