# Generated by Django 4.2.3 on 2023-11-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_areaid_alter_user_cityid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='areaId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='cityId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='relationWithHead',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sectId',
            field=models.IntegerField(),
        ),
    ]
