# Generated by Django 4.2.3 on 2023-11-16 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_user_areaid_alter_user_cityid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='permanentAddress',
        ),
    ]
