# Generated by Django 4.2.3 on 2023-11-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_address_user_permanentaddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emailId',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bloodGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='maritalStatus',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='user',
            name='relationWithHead',
        ),
        migrations.AddField(
            model_name='user',
            name='bloodGroupId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='maritalStatusId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='professionId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='relationId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
