# Generated by Django 4.2.3 on 2023-11-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_rename_emailid_user_email_remove_user_bloodgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationId',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
