# Generated by Django 4.2.3 on 2023-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_user_relationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
